name: Terraform Apply

on:
  push:
    branches: ['main']
    paths:
      - '**.tf'
      - '.terraform.lock.hcl'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  apply:
    name: apply
    runs-on: ubuntu-latest
    environment: prod    # we'll create/protect this env in a sec
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS creds (lab keys)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5

      - name: Terraform init
        run: terraform init -input=false

      - name: Terraform apply
        run: terraform apply -auto-approve

      - name: Show outputs
        run: |
          echo "## Terraform outputs" >> $GITHUB_STEP_SUMMARY
          terraform output -json | jq -r '
            to_entries[] | "- **\(.key)**: \(.value.value)"
          ' >> $GITHUB_STEP_SUMMARY
