name: Terraform CD

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  id-token: write

concurrency:
  group: tf-cd-main
  cancel-in-progress: false

jobs:
  cd:
    runs-on: ubuntu-latest
    environment: prod         # optional: add required reviewers in repo Settings → Environments → prod
    env:
      AWS_REGION: ${{ vars.AWS_REGION }}
      ROLE_ARN: ${{ secrets.AWS_ROLE_TO_ASSUME }}
      MY_IP: ${{ secrets.MY_IP }}     # may be empty
      TF_PLUGIN_CACHE_DIR: ~/.terraform.d/plugin-cache
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create plugin cache dir
        run: mkdir -p "$TF_PLUGIN_CACHE_DIR"

      - name: Cache Terraform providers
        uses: actions/cache@v4
        with:
          path: ~/.terraform.d/plugin-cache
          key: ${{ runner.os }}-tf-plugin-${{ hashFiles('**/.terraform.lock.hcl') }}
          restore-keys: |
            ${{ runner.os }}-tf-plugin-

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Configure AWS (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Who am I?
        run: aws sts get-caller-identity

      - name: Set TF var defaults
        shell: bash
        run: |
          echo "TF_VAR_my_ip=${MY_IP:-0.0.0.0/32}" >> "$GITHUB_ENV"

      - name: Clean previous TF dir
        run: rm -rf .terraform

      - name: Init backend
        run: terraform init -input=false -reconfigure -upgrade

      - name: Select/create workspace
        run: terraform workspace select prod || terraform workspace new prod

      - name: Validate
        run: terraform validate -no-color

      - name: Plan
        run: terraform plan -input=false -no-color -out=plan.out

      - name: Apply
        run: terraform apply -input=false -auto-approve plan.out
